# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      remix-dependencies:
        patterns:
          - "@remix-run/*"
      production-dependencies:
        dependency-type: production
        exclude-patterns:
          - "@remix-run/*"
      development-dependencies:
        dependency-type: development
        exclude-patterns:
          - "@remix-run/*"
  - package-ecosystem: "npm"
    directory: "/sanity"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
