name: Deploy Sanity Studio
on:
  push:
    branches: [ main ]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: sanity deploy
    defaults:
      run:
        working-directory: sanity
    steps:
      - uses: actions/checkout@v2
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: deploy
